android.useAndroidX=true
android.enableJetifier=false
org.gradle.jvmargs=-Xmx2g -Dfile.encoding=UTF-8
org.gradle.workers.max=2
org.gradle.caching=false
kotlin.compiler.execution.strategy=in-process
kotlin.incremental=true
kapt.include.compile.classpath=false
kapt.incremental.apt=true
ksp.incremental=true
