package com.alibaba.android.arouter.compiler.ksp;

import com.google.devtools.ksp.processing.CodeGenerator;
import com.google.devtools.ksp.processing.Dependencies;
import com.squareup.javapoet.ClassName;
import com.squareup.javapoet.JavaFile;
import com.squareup.javapoet.MethodSpec;
import com.squareup.javapoet.ParameterizedTypeName;
import com.squareup.javapoet.TypeSpec;
import com.squareup.javapoet.WildcardTypeName;
import java.io.IOException;
import java.io.OutputStream;
import java.io.OutputStreamWriter;
import java.io.Writer;
import java.nio.charset.StandardCharsets;
import java.util.List;
import java.util.Map;
import javax.lang.model.element.Modifier;

/** Generates the existing register-plugin and runtime interceptor contract. */
final class InterceptorEmitter {
    private final CodeGenerator generator;

    InterceptorEmitter(CodeGenerator generator) {
        this.generator = generator;
    }

    void emit(String module, List<InterceptorModel> interceptors, Dependencies dependencies)
            throws IOException {
        ClassName contract = ClassName.get("com.alibaba.android.arouter.facade.template", "IInterceptor");
        MethodSpec.Builder method = MethodSpec.methodBuilder("loadInto")
                .addAnnotation(Override.class)
                .addModifiers(Modifier.PUBLIC)
                .addParameter(ParameterizedTypeName.get(ClassName.get(Map.class),
                        ClassName.get(Integer.class), ParameterizedTypeName.get(ClassName.get(Class.class),
                                WildcardTypeName.subtypeOf(contract))), "interceptors");
        for (InterceptorModel interceptor : interceptors) {
            method.addStatement("interceptors.put($L, $T.class)",
                    interceptor.priority, interceptor.implementation);
        }
        String name = "ARouter$$Interceptors$$" + module;
        JavaFile file = JavaFile.builder(RouteEmitter.PACKAGE, TypeSpec.classBuilder(name)
                .addModifiers(Modifier.PUBLIC)
                .addJavadoc("Generated by ARouter KSP. Do not edit.\n")
                .addSuperinterface(ClassName.get("com.alibaba.android.arouter.facade.template", "IInterceptorGroup"))
                .addMethod(method.build()).build()).build();
        // Retain an empty registry after deleting the final interceptor. KSP
        // removes its prior aggregate output and the register plugin sees no stale entries.
        try (OutputStream stream = generator.createNewFile(dependencies, RouteEmitter.PACKAGE, name, "java");
                Writer writer = new OutputStreamWriter(stream, StandardCharsets.UTF_8)) {
            file.writeTo(writer);
        }
    }
}
